# 日志文件配置路径
spring:
  application:
    name: xuecheng-plus-content-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.65:3306/xcplus_content?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: mysql

logging:
 config: classpath:log4j2-dev.xml
